import ApplicationProviders from "@/components/ApplicationProviders";
import { Box } from "@chakra-ui/react";
import { DM_Sans } from "next/font/google";
import "./globals.css";

const dmSans = DM_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={dmSans.className}>
        <ApplicationProviders>
          <Box p={{ base: "3rem", lg: "10rem" }} h={"100%"}>
            {children}
          </Box>
        </ApplicationProviders>
      </body>
    </html>
  );
}
